name: "Wazuh Agent"
description: "Wazuh Agent add-on for Home Assistant: enrolls an agent and forwards logs to a Wazuh Manager."
version: "0.2.6.1"
slug: "wazuh_agent"
init: false

arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto

options:
  manager_address: ""
  agent_name: "home-assistant"
  agent_group: ""
  enrollment_port: 1515
  communication_port: 1514
  enrollment_key: ""
  force_reenroll: false
  debug_dump_config: true

schema:
  manager_address: str
  agent_name: str
  agent_group: str?
  enrollment_port: int
  communication_port: int
  enrollment_key: password
  force_reenroll: bool?
  debug_dump_config: bool?

map:
  - config:ro
  - ssl:ro
  - share:rw
  - /run/log/journal:ro
  - /var/log/journal:ro
  - /etc/machine-id:ro
