name: "Wazuh Agent"
version: "0.1.0"
slug: "wazuh_agent"
description: "Wazuh Agent for forwarding Home Assistant logs to a Wazuh Manager."
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
boot: auto
ingress: false
host_network: false
privileged: []
map:
  - config:ro
  - share:ro
  - ssl:ro
options:
  manager_address: "192.168.1.39"
  agent_name: "home-assistant"
  agent_group: "homeassistant"
schema:
  manager_address: str
  agent_name: str
  agent_group: str
