name: "Wazuh Agent"
version: "0.1.5"
slug: "wazuh_agent"
description: "Wazuh Agent for forwarding Home Assistant logs to a Wazuh Manager."
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
boot: auto
ingress: false
host_network: false
privileged: []
map:
  - config:ro
  - share:ro
  - ssl:ro
options:
  manager_address: "192.168.1.39"
  agent_name: "home-assistant"
  agent_group: ""        # opcionalno
  enrollment_port: 1515
  communication_port: 1514
  enrollment_key: ""     # obavezno (UI će tražiti)

schema:
  manager_address: str
  agent_name: str
  agent_group: "str?"    # ✅ opcionalno (nema zvjezdice)
  enrollment_port: int
  communication_port: int
  enrollment_key: str    # ✅ obavezno (ima zvjezdicu)
